### ISSUE TITLE
Unable to use -y when creating a profile

### ISSUE THREAD

**Issue by unparalleled-js** [code42/code42cli#158]
### Description

Unable to -y for `code42 profile create`. 

### Steps to Reproduce

1. Use `code42 profile create -u`
2. Notice that it says `-y` is not an option

### Expected Behavior
To use `-y` and afford automating creating a profile. The use case could be to create the test profile if one does not exist already before running the commands.

### Actual Behavior
Failure

### Basic Information

- code42cli version: 1.0.0
- python version: 1.81
- operating system: Mac OS

**Comment by timabrmsn** [comment]
This was implemented in #219.
