### ISSUE TITLE
[Enhancement] End support for python 3.5

### ISSUE THREAD

**Issue by alanag13** [code42/code42cli#166]
## Summary

Python 3.5 reached official end-of-life in September. Ending support for it allows us to take advantage of new language features and enables us to take on modern dependencies that could be useful to the cli such as `pandas`.

A large part of the migration effort for this can probably be greatly simplified by changing our `pyupgrade` style hook to be 3.6+.

**Comment by timabrmsn** [comment]
This was implemented in #167.
