### ISSUE TITLE
[Enhancement] Updating profile does not know to use the default profile when not specifying `-n`

### ISSUE THREAD

**Issue by unparalleled-js** [code42/code42cli#205]
## Summary
`code42 profile update` command requires `-n`.  Like other profile commands, when `-n` is not specified, it should know to use the default profile.

Also, if the user only wishes to change a single property, they still have to specify all of the other ones.  For example, if I just want to change my server address, I have to still supply my username.

## Proposed API

Allow command:

`code42 profile update -s 127.0.0.1:4200`

that only updates the server address for the default profile.

## Intended Use Case
To be able to easily change the server address.

**Comment by 3nin6** [comment]
Should the server and username options also be made required=False under the similar assumption that if the flag is not set, then use what already exists?
