### ISSUE TITLE
[Enhancement] Support 2FA

### ISSUE THREAD

**Issue by ceciliastevens** [code42/code42cli#255]
## Summary
Py42 [allows](https://py42docs.code42.com/en/stable/userguides/basics.html#initialization) authentication using Code42's two-factor authentication/TOTP implementation. The CLI currently doesn't support using this, and returns an error if you attempt to create a profile using an account with two-factor authentication enabled.

## Proposed API

Because of the time-sensitive nature of the one-time passwords, we'd need to accept the code at command run-time. Ideally we would allow it to be passed as a parameter:

```
$ code42 example command --totp 123456
````

If the user doesn't provide the TOTP in the command, but Code42 requires it, we should prompt:

```
$ code42 example command
Please input the time-based one-time password for exampleuser@code42.com: 123456
```

Long-running commands may require a second prompt if the token expires.

## Intended Use Case
Support Code42's existing 2FA implementation when using the CLI.

**Comment by timabrmsn** [comment]
Yeah, we should definitely be able to support 2FA users. I'll open an internal ticket for planning/prioritization.

**Comment by timabrmsn** [comment]
2FA support was added in 1.6.0
