### ISSUE TITLE
code42cli on headless ubuntu 20.04, how to unlock the keyring?

### ISSUE THREAD

**Issue by mbassett** [code42/code42cli#323]
Hey folks, I am migrating my code42cli solution from an older ubuntu 16.04 box that is using flatfile authentication to an ubuntu 20.04 box.  The new box won't let me setup flat file auth and is forcing me to use python keyring=18.0.1

However, I can find no way to invoke the client from script(cron) that doesn't prompt me for the keyring password.
How do I programatically provide the keyring password so that I can call code42cli functions from script?

**Comment by alanag13** [comment]
Hi @mbassett !

You should be able to force the use of the flat file for auth by providing some configuration to keyring. Try the following:
Run this to and note the output:

```bash
python -c "import keyring.util.platform_; print(keyring.util.platform_.config_root())"
```
This will return a directory path. Create a file named `keyringrc.cfg` in that directory with the following contents:

```
[backend]
default-keyring=keyrings.alt.file.PlaintextKeyring
```

To verify, you can start a python interactive shell:

```bash
python
>>> import keyring
>>> keyring.get_keyring()
```

This should output something like:

```
<PlaintextKeyring with no encyption v.1.0 at /<user-specific-dir-omitted>/python_keyring/keyring_pass.cfg>
```

Hope this helps!

**Comment by mbassett** [comment]
@alanag13 
Excellent thank you this is exactly what I needed.
