### ISSUE TITLE
[Bug] Issue with Running Code42Cli on-Prem solution

### ISSUE THREAD

**Issue by ishackigozi** [code42/code42cli#353]
### Steps to Reproduce

1. I get this error  Found for url: https://crashplan.na.corp.samsungelectronics.net:4285/api/v3/auth/jwt?useBody=True
2. Correct API Url is [ Base URL: crashplan.na.corp.samsungelectronics.net:4285/c42api/v3
3. Where can I change the URL in the code in the python env.

For example if I run this "code42 devices list --active -f CSV" I get this error.

Error: Unknown problem validating connection.
View details in /home/i.kigozi/.code42cli/log/code42_errors.log

Please assist me on how to change the api url in the python env.
code42cli               1.8.0

### Basic Information

- code42cli version: 
i.kigozi@SRA-9000000741:~$ code42 -h
Usage: code42 [OPTIONS] COMMAND [ARGS]...

   dP""b8  dP"Yb  8888b. 888888  dP88  oP"Yb.
  dP   `" dP   Yb 8I  Yb 88__   dP 88  "' dP'
  Yb      Yb   dP 8I  dY 88""  d888888   dP'
   YboodP  YbodP  8888Y" 888888    88  .d8888

  code42cli version 1.8.0, by Code42 Software. powered by py42 version
  1.20.0.

i.kigozi@SRA-9000000741:~$ python --version
Python 2.7.18

Operating System -"Ubuntu 20.04.3 LTS"

- python version: <!-- get using `code42 -h`--
- operating system:

**Comment by timabrmsn** [comment]
Hi @ishackigozi, 

This was due to the [change in py42 1.19.3](https://github.com/code42/py42/blob/main/CHANGELOG.md#1193---2021-11-09) which moved all the `c42api/v3` endpoints to a standardized api versioning scheme in the cloud. 

Since support for on-premises installations is end-of-life at the end of this month, we won't be altering new versions of py42 for on-premise deployments, but you should be able to downgrade your py42 installation to revert to the previous urls compatible with your on-premise server: 

```
pip uninstall py42
pip install py42==1.19.2
``

I should also note that the [CLI version 1.11.1](https://github.com/code42/code42cli/blob/main/CHANGELOG.md#changed-1) updates the minimum py42 requirement to 1.19.3, so CLI version 1.11.0 will also be the latest you'll be able to upgrade to for on-premise servers.

**Comment by ishackigozi** [comment]
Thank you so much. Works Like a Charm

**Comment by ishackigozi** [comment]
Hello Tim,
I am trying to deactivate several devices. For some reason, I used the same format of the columns for the .csv file obtained from running this command. 
code42 devices list --active -f CSV > output.csv

I included the devices I wanted to deactivate in a .csv and run the command "code42 devices bulk deactivate  List.csv -f CSV > deactivation_results.csv"

In the deactivation_results.csv, I am getting this error


False: The device with GUID   'SRA2030008499	SRA2030008499	Active	2022-02-09T11:13:36.269-05:00	2021-02-03T15:28:09.802-05:00	8.2.1	win	10.0.19041	7.90E+17'   was not found.
--

Please advise on how I am supposed to have the columns in the .csv

Thanks Again,
Ishac

**Comment by timabrmsn** [comment]
Two things I see here:

- The `userUid` in the error was converted to scientific notation (`7.90E+17`), which tells me this was probably edited with Excel. Use the following steps to import the CSV to make sure Excel isn't converting the large number uids: https://support.code42.com/Incydr/Admin/Monitoring_and_managing/Import_CSV_reports_to_Microsoft_Excel
- The columns in the error aren't separated by commas, so make sure after editing the file is saved/exported to CSV correctly with commas separating each column. You might want to open the file in a plain text editor to make sure it looks similar to this: 
```
computerId,guid,name,osHostname,status,lastConnected,creationDate,productVersion,osName,osVersion,userUid
123456789,987654321182727,DESKTOP-ABCDEFG,DESKTOP-ABCDEFG,"Active, Deauthorized",2020-12-28T09:13:27.910Z,2020-09-10T13:40:22.188Z,8.5.0,win,10.0.17134,9233020000000000
123456789,987654321182727,DESKTOP-XYZ123,DESKTOP-XYZ123,"Active, Deauthorized",2019-12-23T10:59:22.114Z,2019-12-04T10:03:48.252Z,7.4.0,win,10.0,9233020000000000
```

**Comment by ishackigozi** [comment]
Hello, My apologies for not communicating ahead of time. 
I was able to get the csv file. Although, the deactivation does not work
Any pointers please. 
[deactivation_results.csv](https://github.com/code42/code42cli/files/8143047/deactivation_results.csv)
